name: Build and Deploy 
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        make install
        pip install build
    
    - name: Linting
      run: |
        make lint
    
    - name: Testing
      run: |
        make test
    
    - name: Building Package
      run: |
        make build
    
    - name: Upload Python Package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/*
    
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build d_img
      run: |
        docker build -f Dockerfile -t kag3/emotionlens:latest .
    - name: Push d_img on DockerHub
      run: |
        docker push kag3/emotionlens:latest

    - name: Save d_img as artifact
      continue-on-error: true
      run: |
        docker save kag3/emotionlens:latest -o emotionlens-latest.tar || true
        gzip emotionlens-latest.tar || true
    - name: Upload d_img artifact
      if: hashFiles('emotionlens-latest.tar.gz') != ''
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: emotionlens-latest.tar.gz